import { WeaponConfig } from './types';

export function createDefaultWeapons(): WeaponConfig[] {
  const weapons: WeaponConfig[] = [
    {
      id: `weapon_line_${Math.random().toString(36).substring(2, 6)}`,
      name: 'Прямой удар (Линия)',
      prepTime: 0.2,
      recoveryTime: 0.3,
      prepTurnSlow: 0.5,
      recoveryTurnSlow: 0.8,
      prepMoveSlow: 0.5,
      recoveryMoveSlow: 0.8,
      baseDamage: 25,
      minMultiplier: 0.8,
      maxMultiplier: 1.2,
      critChance: 0.15,
      critMultiplier: 2.0,
      hitZoneType: 'forward_line',
      length: 150,
    },
    {
      id: `weapon_angle_${Math.random().toString(36).substring(2, 6)}`,
      name: 'Угловой взмах (30°)',
      prepTime: 0.25,
      recoveryTime: 0.35,
      prepTurnSlow: 0.4,
      recoveryTurnSlow: 0.7,
      prepMoveSlow: 0.4,
      recoveryMoveSlow: 0.7,
      baseDamage: 20,
      minMultiplier: 0.9,
      maxMultiplier: 1.1,
      critChance: 0.1,
      critMultiplier: 1.8,
      hitZoneType: 'angle',
      length: 100,
      angle: Math.PI / 6,
    },
    {
      id: `weapon_radius_${Math.random().toString(36).substring(2, 6)}`,
      name: 'Радиусная аура',
      prepTime: 0.3,
      recoveryTime: 0.4,
      prepTurnSlow: 0.6,
      recoveryTurnSlow: 0.9,
      prepMoveSlow: 0.6,
      recoveryMoveSlow: 0.9,
      baseDamage: 30,
      minMultiplier: 0.8,
      maxMultiplier: 1.3,
      critChance: 0.1,
      critMultiplier: 2.5,
      hitZoneType: 'radius',
      radius: 50,
    },
    {
      id: `weapon_shrapnel_${Math.random().toString(36).substring(2, 6)}`,
      name: 'Шрапнель (Веер)',
      prepTime: 0.4,
      recoveryTime: 0.5,
      prepTurnSlow: 0.3,
      recoveryTurnSlow: 0.6,
      prepMoveSlow: 0.3,
      recoveryMoveSlow: 0.6,
      baseDamage: 15,
      minMultiplier: 0.7,
      maxMultiplier: 1.5,
      critChance: 0.25,
      critMultiplier: 2.0,
      hitZoneType: 'shrapnel',
      length: 120,
      angle: Math.PI / 3,
      rayCount: 5,
    },
    {
      id: `weapon_offset_radius_${Math.random().toString(36).substring(2, 6)}`,
      name: 'Выносная сфера',
      prepTime: 0.2,
      recoveryTime: 0.3,
      prepTurnSlow: 0.5,
      recoveryTurnSlow: 0.8,
      prepMoveSlow: 0.5,
      recoveryMoveSlow: 0.8,
      baseDamage: 22,
      minMultiplier: 0.85,
      maxMultiplier: 1.15,
      critChance: 0.15,
      critMultiplier: 2.0,
      hitZoneType: 'offset_radius',
      offsetDistance: 70,
      radius: 35,
    },
  ];

  for (let i = weapons.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [weapons[i], weapons[j]] = [weapons[j], weapons[i]];
  }

  return weapons;
}